/**
 * @file user_app.cpp
 * @brief User-editable application logic — compiled alongside the ioTech framework.
 *
 * This file is generated by ioTech AI and can be edited by the installer.
 * Declare driver objects as global instances, initialize in user_setup(),
 * and write control logic in user_loop().
 *
 * The framework calls:
 *  - user_setup() once after io_driver_init() (during app_main)
 *  - user_loop() periodically in the heartbeat task (before MQTT telemetry publish)
 *
 * NOTE: Keep extern "C" on both entry points to ensure C linkage
 *       from the C framework (main.c / mqtt_manager.c).
 */

#include <iotech.hpp>

/* ── User driver declarations ──────────────────────────────────────── */
/* TODO: AI-generated code will populate this section. */
/* Example:
 *   DHT22 dht(32);
 *   Relay riego(23, "Bomba de riego");
 */

/* ── Entry points (C linkage for main.c / mqtt_manager.c) ──────────── */

extern "C" void user_setup() {
    /* TODO: AI-generated code will call begin() on each driver instance.
     * Example:
     *   dht.begin();
     *   riego.begin();
     */
}

extern "C" void user_loop() {
    /* TODO: AI-generated logic — reads sensors and acts on rules.
     * Example:
     *   float temp = dht.readTemperature();
     *   if (temp <= 12.0f) { riego.on(); } else { riego.off(); }
     *   delay(2000);
     */
}
